"""01_initial-db

Revision ID: 6f404cfbb52b
Revises: 
Create Date: 2023-11-03 09:31:56.901266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f404cfbb52b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_urls',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('initial_url', postgresql.UUID(as_uuid=True),
                              nullable=False, unique=True),
                    sa.Column('short_url', postgresql.UUID(as_uuid=True),
                              nullable=False, unique=True),
                    sa.Column('created_at', sa.DateTime(), default=sa.text('now()')),
                    sa.Column('active', sa.Boolean(), default=True),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_urls_created_at'), 'short_urls', ['created_at'], unique=False)
    op.create_table('usages',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('url_id', sa.INTEGER(), nullable=False),
                    sa.Column('usage_datetime', sa.DateTime(), default=sa.text('now()')),
                    sa.Column('client_host', sa.String(), nullable=False),
                    sa.Column('client_port', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['url_id'], ['short_urls.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usages_usage_datetime'), 'usages', ['usage_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usages', sa.Column('blocked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_usages_usage_datetime'), table_name='usages')
    op.alter_column('usages', 'usage_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('usages', 'url_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usages', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_short_urls_created_at'), table_name='short_urls')
    op.alter_column('short_urls', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('short_urls', 'short_url',
               existing_type=sqlalchemy_utils.types.url.URLType(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('short_urls', 'initial_url',
               existing_type=sqlalchemy_utils.types.url.URLType(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('short_urls', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
