"""01_initial-db

Revision ID: b515ebc3dc8d
Revises: 
Create Date: 2023-10-22 10:27:42.707455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b515ebc3dc8d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('short_urls', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('short_urls', 'initial_url',
               existing_type=sa.VARCHAR(),
               type_=sqlalchemy_utils.types.url.URLType(),
               existing_nullable=False)
    op.alter_column('short_urls', 'short_url',
               existing_type=sa.VARCHAR(),
               type_=sqlalchemy_utils.types.url.URLType(),
               existing_nullable=False)
    op.alter_column('short_urls', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_short_urls_created_at'), 'short_urls', ['created_at'], unique=False)
    op.alter_column('usages', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('usages', 'url_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usages', 'usage_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_usages_usage_datetime'), 'usages', ['usage_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usages_usage_datetime'), table_name='usages')
    op.alter_column('usages', 'usage_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('usages', 'url_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usages', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_short_urls_created_at'), table_name='short_urls')
    op.alter_column('short_urls', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('short_urls', 'short_url',
               existing_type=sqlalchemy_utils.types.url.URLType(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('short_urls', 'initial_url',
               existing_type=sqlalchemy_utils.types.url.URLType(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('short_urls', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
